steps:
- bash: |
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    az storage blob download -c avs -f virtualservice-0.1.1.tgz -n virtualservice-0.1.1.tgz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=amecodegenstorage
    tar -xzvf virtualservice-0.1.1.tgz
    sudo cp package/localhost-ca.crt /usr/local/share/ca-certificates/
    sudo update-ca-certificates
    
    cd package
    npm install
    . initiate.sh
    tsc
    sudo node dist/src/main.js 1>$(Pipeline.Workspace)/s/mockserver.log 2>&1 &
    # sudo node dist/src/main.js &
    sleep 3m

    ps -eaf |grep node
    netstat -l
  displayName: 'setup mock server'
