parameters:
  - name: sdk
    type: string

  - name: specRepoUrl
    type: string

  - name: specRepoBaseBranch
    type: string

  - name: sdkRepoUrl
    type: string

  - name: sdkRepoBaseBranch
    type: string

steps:
  - bash: |
      curl -X PATCH -H "Content-Type: application/json" https://$(CodegenApp_Server)/codegenerations/$(CodeGenerationName) -d '{"updateParameters": {"status": "in_progress","lastPipelineBuildID": "$(Build.BuildId)"}}'
    displayName: Notify Sdk Generation Server to Start

  - bash: |
        git clone --branch ${{ parameters.specRepoBaseBranch }} ${{ parameters.specRepoUrl }}
    displayName: Clone Spec Repo
    workingDirectory: ../

  - bash: |
        git clone --branch ${{ parameters.sdkRepoBaseBranch }} ${{ parameters.sdkRepoUrl }}
    displayName: Clone Sdk Repo 
    workingDirectory: ../

  - task: Npm@1
    displayName: Npm Install Dependencies of Sdk Automation Tool
    inputs:
      workingDir: tools/sdk-automation
      command: install


  - task: Npm@1
    displayName: Build Sdk Automation Tool
    inputs:
      workingDir: tools/sdk-automation
      command: custom
      customCommand: run build

  - task: Npm@1
    displayName: Pack Sdk Automation Tool
    inputs:
      workingDir: tools/sdk-automation
      command: custom
      customCommand: pack

  - bash: |
      PACKAGE_TGZ=`ls sdk-automation-*.tgz`
      npm install -g ${PACKAGE_TGZ}
    displayName: Install Sdk Automation Tool
    workingDirectory: tools/sdk-automation
 