parameters:
- name: subTaskKey
  type: string
  default: ''

steps:
# - script: |
#     echo $pwd
#     # tar -czvf $(TARGET)-$(ResourceProvider)-generated.tar.gz generated/$(ResourceProvider)
#     tar -czvf $(TARGET)-$(ResourceProvider)-generated.tar.gz $(Artifact)
#     az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
#     az storage blob upload -c sdk-pipeline -f $(TARGET)-$(ResourceProvider)-generated.tar.gz -n $(TARGET)/$(TARGET)-$(ResourceProvider)-generated.tar.gz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=sdkpipeline
#   condition: always()
#   displayName: 'After $(TASK_KEY)'
- bash: |
    pwd
    ls -l
    tar -czvf $(CodeGenerationName)-$(Build.BuildId)-$(TASK_KEY)-log.tar.gz *.log
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    az storage blob upload -c sdk-pipeline -f $(CodeGenerationName)-$(Build.BuildId)-$(TASK_KEY)-log.tar.gz -n log/$(Build.BuildId)/$(CodeGenerationName)-$(Build.BuildId)-$(TASK_KEY)-log.tar.gz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=sdkpipeline
  condition: always()
  displayName: 'upload log'
- bash: |
    set -x
    npm install -g codegenapp
    pwd
    ls -l
    ls -l /home/vsts/work
    publish-codegen-pipeline-result --codegen=$(CodeGenerationName) --pipelineBuildId=$(Build.BuildId) --task=$(TASK_KEY) --status=completed --result=$(Task_Result) --logfile=$(TASK_KEY).log --pipelineLog=pipe.log
    az storage blob upload -c sdk-pipeline -f pipe.log -n log/$(Build.BuildId)/$(CodeGenerationName)-$(Build.BuildId)-$(TASK_KEY)-result.log --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=sdkpipeline

    # publish result to cosmos db
    sudo apt-get install jq -y
    result=`jq . pipe.log`
    # curl -X POST -H "Content-Type: application/json" https://sdk-pipeline.test.azure-devex-tools.com/codegenerations/$(CodeGenerationName)/taskResult -d '{"pipelineBuildId":$(Build.BuildId), "taskResult": '"$result"'}'
    curl -X POST -H "Content-Type: application/json" https://sdk-pipeline.test.azure-devex-tools.com/codegenerations/$(CodeGenerationName)/taskResult -d '{"pipelineBuildId":"$(Build.BuildId)", "taskResult": '"$result"'}'

    if [ "$(Task_Result)" != "success" ]; then
      codePR=$(curl -X PATCH -H "Content-Type: application/json" https://sdk-pipeline.test.azure-devex-tools.com/codegenerations/$(CodeGenerationName) -d '{"updateParameters": {"status": "completed"}}')
      # exit 1
    fi
  condition: always()
  displayName: 'upload pipeline result'
# - bash: |
#     codePR=$(curl -X POST -H "Content-Type: application/json" https://sdk-pipeline.test.azure-devex-tools.com/depthCoverage/generatePullRequest -d '{"org":"'"$org"'", "repo":"'"$repo"'", "title":"{$(OnboardType) coverage, not merge} pull request of $(ResourceProvider)", "branch":"$(WORKBRANCH)-code", "base":"'"$base"'"}')
#   displayName: 'update code generation status'
