steps:
- bash: |
    set -x
    # bash ./scripts/bash/$(SDK)/Build.sh $(Pipeline.Workspace)/s/azure-sdk-for-go/sdk/$(ResourceProvider)/arm$(ResourceProvider) >>$(Pipeline.Workspace)/s/$(TASK_KEY).log 2>&1
    cmd=`node dist/TaskEngine.js "config.json" "Build" "$(SDK)"`
    $cmd $(Pipeline.Workspace)/s/azure-sdk-for-go/sdk/$(ResourceProvider)/arm$(ResourceProvider) >>$(Pipeline.Workspace)/s/$(TASK_KEY).log 2>&1
    if [ "$?" != "0" ]; then
      echo -e "\e[31m[$(date -u)] ERROR: [$(ResourceProvider)]: build code failed"
      echo "##vso[task.setvariable variable=Task_Result]failure"
      exit 1
    fi
  displayName: 'Build'