steps:
- script: |
    pwd
    cd $(Pipeline.Workspace)/s
    # tar -czvf $(TARGET)-$(ResourceProvider)-generated.tar.gz generated/$(ResourceProvider)
    tar -czvf $(CodeGenerationName)-$(Build.BuildId)-generated.tar.gz $(Artifact)
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    az storage blob upload -c depthcoverage -f $(CodeGenerationName)-$(Build.BuildId)-generated.tar.gz -n $(CodeGenerationName)-$(Build.BuildId)-generated.tar.gz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=depthcoverage
  condition: always()
  displayName: 'Upload code'