steps:
- bash: |
    # copy some hack file
    cp scripts/TFMockServer/environments.go $(Pipeline.Workspace)/s/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/Azure/go-autorest/autorest/azure/environments.go
    cp scripts/TFMockServer/sender.go $(Pipeline.Workspace)/s/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/go-azure-helpers/sender/sender.go
  displayName: 'setup terraform mock env'
- bash: |
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    az storage blob download -c avs -f virtualservice-0.1.0.tgz -n virtualservice-0.1.0.tgz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=amecodegenstorage
    tar -xzvf virtualservice-0.1.0.tgz
    cd package
    npm install
    . initiate.sh
    tsc
    sudo node dist/src/main.js 1>$(Pipeline.Workspace)/s/mockserver.log 2>&1 &
    # sudo node dist/src/main.js &
    sleep 3m

    ps -eaf |grep node
    netstat -l
  displayName: 'setup mock server'