steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7.x'
    addToPath: true
    architecture: 'x64'
- bash: |
    ls -l
    pwd
    echo "https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@github.com" > ~/.git-credentials
    git clone --branch $(WORKBRANCH) https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@$(SDK_REPO_URL)
    git clone --branch $(WORKBRANCH) https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@$(SPEC_REPO_URL)
    ls -l

    python --version
    python -m venv ./venv
    # cat ./scripts/config/cli-requirements.txt | xargs -n 1 ./venv/bin/pip install  || echo "some installation failed, but still go on..."
    . venv/bin/activate
    ./venv/bin/pip install azdev
    which azdev
    # azdev setup --cli ./azure-cli -r azure-cli-extensions
    # azdev setup -r ./azure-cli-extensions  //need to modify, for cli-extension
    azdev setup --cli ./azure-cli
    # cat ./azure-cli/src/azure-cli/requirements.py3.Linux.txt |xargs -n 1 ./venv/bin/pip install
    az login --service-principal --username $(SERVICE_PRINCIPE_ID) --password $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    first="./azure-rest-api-specs$(README_FILE)"
    second="readme.az.md"
    readme_file_path=${first/readme.md/$second}
    export extension_name=`cat $readme_file_path | grep extensions | awk '{print $NF}' | tr -d '\r'`
  displayName: 'cli Test Env Setup'