steps:
- bash: |
    . venv/bin/activate
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    
    az storage blob download -c avs -f mockservicehost-0.1.1.tgz -n mockservicehost-0.1.1.tgz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=amecodegenstorage
    tar -xzvf mockservicehost-0.1.1.tgz
    cd package
    npm install
    . initiate.sh
    tsc
    sudo node dist/src/main.js > ../mockserver.log &
    cd $(Pipeline.Workspace)/s
    ls -l
    ls -l package/dist
    ls -l ./venv/lib/
    ls -l ./venv/lib/python*/site-packages/certifi/cacert.pem
    # cat scripts/config/localhost_ca.crt >> ./venv/lib/python*/site-packages/certifi/cacert.pem
    cat package/.ssh/localhost-ca.crt >> ./venv/lib/python*/site-packages/certifi/cacert.pem
    ls -l ./venv/lib/python*/site-packages/certifi/cacert.pem
    # . venv/bin/activate
    which python
    cd package
    export AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1
    az --version
    az cloud register -n virtualCloud --endpoint-resource-manager "https://localhost:8443" --endpoint-active-directory https://login.microsoftonline.com --endpoint-active-directory-graph-resource-id https://graph.windows.net/ --endpoint-active-directory-resource-id https://management.core.windows.net/
    az cloud set -n virtualCloud
    sleep 3m
  displayName: 'setup cli mock env'